Fix a bug in compiling immediate lambdas.
Immediately-called lambdas would start running even when no case matched the arg
spec they were called at; in that case, the VM should just create a partial
application instead.

In this example, the lambda is being called with fixed right argument [].
It should just assign a partial application object to Shape, but instead it
starts calling the function and crashes when it tries to pop a second arg from
the stack.
    Shape: {
       if(x# = 0; y , 0
             if(x[0] ->h == x; y
                h Rec (y , (x#))
               )
            )
      } []
Before:
  thread 'main' panicked at src/vm.rs:595:26:
  called `Option::unwrap()` on a `None` value

This also manifests in simpler situations I didn't think of before, where a
lambda that appears to be called just once can actually be called at multiple
arities by virtue of using `Rec`:
  1 {x Rec + y} 2
thread 'main' panicked at src/vm.rs:596:26:
called `Option::unwrap()` on a `None` value

The solution is to always include an ArgCheck instruction in function
bodies. Later, we can try and do proper inlining instead of just droppping
ArgCheck.